export const IS_HIDDEN = 'IS_HIDDEN';
export const CLICK_IT = 'CLICK_IT';

// GENERAL
export const HANDLER_LOADING = 'HANDLER_LOADING'
export const IS_LOADING = 'IS_LOADING';
export const PUSH_NOTIFICATION = 'PUSH_NOTIFICATION';
export const DISPATCH_HTTP = 'DISPATCH_HTTP';
export const SET_DATABASE = 'SET_DATABASE';
export const SET_SAMPLE_DATABASE = 'SET_SAMPLE_DATABASE';